' err is a builtin, so this should fail with "Expected statement".
err: print